### ISSUE TITLE
"how to flash" readme section

### ISSUE THREAD

**Issue by after-ephemera** [rust-embedded/msp430-quickstart#1]
Hi there! I'm new to MSP430 development and embedded Rust but I have experience with embedded C on other platforms. I'd like to get started developing for the MSP430 with this repo but I am not sure how to flash my binary to the chip once it's built. Can we add a section to the readme to at least point people in the right direction?

**Comment by cr1901** [comment]
Leaving this open, because it's my oversight that it's not in the README.md.

To flash to your chip, you will want to start a session of mspdebug. See [this file](https://github.com/rust-embedded/msp430-quickstart/blob/master/mspdebug.cfg)'s first line for an example invocation.

Then, invoke `msp430-elf-gdb` with the [linked script](https://github.com/rust-embedded/msp430-quickstart/blob/master/mspdebug.gdb). Something like `msp430-elf-gdb -x mspdebug.gdb /path/to/elf/file`. This should load your Rust code onto your MSP430.

**Comment by after-ephemera** [comment]
Thanks @cr1901, this worked for me. I opened #2 to get started on a potential update to the README.

**Comment by cr1901** [comment]
Thank you for doing that for me :D!
